/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Read from environment variables if available (for Netlify deployment)
// Otherwise fall back to hardcoded values (for local development)
export const projectId = import.meta.env.VITE_SUPABASE_URL 
  ? new URL(import.meta.env.VITE_SUPABASE_URL).hostname.split('.')[0]
  : "faczbtutzsrcnlrahifb"

export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY 
  || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhY3pidHV0enNyY25scmFoaWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0OTE3MTMsImV4cCI6MjA4MDA2NzcxM30.2PYn_okTcGJ78VtwEq6uN3ESKBmOb1r6bZALIV10lGc"